### ISSUE TITLE
Mining coins not credits to wallet

### ISSUE THREAD

**Issue by Moawati** [pangz-lab/verus_box-release#8]
Iam mining for 8 hours but not credited to my wallet

**Comment by pangz-lab** [comment]
> Iam mining for 8 hours but not credited to my wallet

Did you create your own wallet address?

If not you have to create first.
If yes, check the faqs here. https://pangz-lab.github.io/verusminer/

Mining pool have different mining schedule and minimum payment before you'll get paid.
